### ISSUE TITLE
报错

### ISSUE THREAD

**Issue by creeperCN** [FlysoftBeta/QQNTim#118]
is not recognized as an internal or external command,
operable program or batch file

**Comment by creeperCN** [comment]
The argument '.\install.ps1' to the -File parameter does not exist. Provide the path to an existing '.ps1' file as an argument to the -File parameter.

**Comment by FlysoftBeta** [comment]
能截一张完整的图吗

**Comment by creeperCN** [comment]
The argument '.\install.ps1' to the -File parameter does not exist. Provide the path to an existing '.ps1' file as an argument to the -File parameter.
Windows PowerShell
Copyright (C) Microsoft Corporation. All rights reserved.

Try the new cross-platform PowerShell https://aka.ms/pscore6

安装时出现错误。如果你认为这是 QQNTim 的问题，请向我们报告此问题 。
'��试手动安装。' is not recognized as an internal or external command,
operable program or batch file.



在 2023-07-11 19:31:30，"Flysoft" ***@***.***> 写道：

能截一张完整的图吗

**Comment by 0769559** [comment]
![image](https://github.com/Flysoft-Studio/QQNTim/assets/22361624/40da1496-651f-41fb-8f39-e9da132d5574)

**Comment by 0769559** [comment]
> ![image](https://user-images.githubusercontent.com/22361624/253238437-40da1496-651f-41fb-8f39-e9da132d5574.png)

我这自己知道原因了 原来是还有个叫“_”的文件夹被我下意识忽略成是个返回上层的意思 只解压了那4个cmd和sh文件。后面重新确认的时候还奇怪怎么压缩包5.7mb，而这4个文件都是文本 不应该这么大才对

**Comment by FlysoftBeta** [comment]
> The argument '.\install.ps1' to the -File parameter does not exist. Provide the path to an existing '.ps1' file as an argument to the -File parameter. Windows PowerShell Copyright (C) Microsoft Corporation. All rights reserved. Try the new cross-platform PowerShell https://aka.ms/pscore6 安装时出现错误。如果你认为这是 QQNTim 的问题，请向我们报告此问题 。 '��试手动安装。' is not recognized as an internal or external command, operable program or batch file. 在 2023-07-11 19:31:30，"Flysoft" ***@***.***> 写道： 能截一张完整的图吗 — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you authored the thread.Message ID: ***@***.***>

应该是没解压完整导致的
