### ISSUE TITLE
NT API

### ISSUE THREAD

**Issue by FlysoftBeta** [FlysoftBeta/QQNTim#13]
- [x] 发送消息 https://github.com/FlysoftBeta/QQNTim/pull/9
- [x] 接收消息 https://github.com/FlysoftBeta/QQNTim/pull/9
- [x] 文本消息支持 https://github.com/FlysoftBeta/QQNTim/pull/9
- [x] 表情消息支持 https://github.com/FlysoftBeta/QQNTim/pull/15
- [x] 图片消息支持 https://github.com/FlysoftBeta/QQNTim/pull/15 https://github.com/Flysoft-Studio/QQNTim/pull/37
- [x] 撤回消息 https://github.com/FlysoftBeta/QQNTim/pull/18
- [x] 获取好友、群列表 https://github.com/FlysoftBeta/QQNTim/pull/26
- [x] 获取历史消息 https://github.com/Flysoft-Studio/QQNTim/pull/29
- [x] 提供更多示例 https://github.com/Flysoft-Studio/QQNTim/pull/40
- [ ] 加群、加好友
- [ ] 退群、删好友
- [ ] 踢人
- [ ] 拉人
- [ ] 发送合并转发消息
- [x] HTTP API/WebSocket API https://github.com/Rei1mu/QQNTim-Plugin-NTHttp
- [ ] ~~Koishi 支持~~

**Comment by Rei1mu** [comment]
加群加好友这些建议不做，图片支持优先

**Comment by FlysoftBeta** [comment]
> 加群加好友这些建议不做，图片支持优先

任务优先级是从上到下的，我会先完成基本功能
