### ISSUE TITLE
QQNT 9.9.1版本已经无法使用QQNTim（隔壁LiteLoader一样

### ISSUE THREAD

**Issue by ApartTUSITU** [FlysoftBeta/QQNTim#153]
崽种腾讯已经给package.json加上签名校验，导致现在使用QQNTim和LiteLoader会提示文件损坏，隔壁已经有issue了：https://github.com/mo-jinran/LiteLoaderQQNT/issues/50

理论上破解掉签名校验就可以

**Comment by FlysoftBeta** [comment]
请更新到 2.1.0: https://github.com/Flysoft-Studio/QQNTim/releases/tag/v2.1.0
