### ISSUE TITLE
添加防撤回插件之后无法打开LiteLoaderQQNT管理

### ISSUE THREAD

**Issue by PaSSw0rds** [FlysoftBeta/QQNTim#164]
![image](https://github.com/Flysoft-Studio/QQNTim/assets/17513790/e0c0a8b4-4f98-4add-8c19-d9e85ee70d04)

**Comment by FlysoftBeta** [comment]
请使用 F12 打开开发者工具并切到 `Console` 栏进行截图。

**Comment by PaSSw0rds** [comment]
![image](https://github.com/Flysoft-Studio/QQNTim/assets/17513790/15ec6731-091e-4e2b-bd7f-b6aec151e29a)

**Comment by FlysoftBeta** [comment]
你使用的liteloader版本是？

**Comment by PaSSw0rds** [comment]
![image](https://github.com/Flysoft-Studio/QQNTim/assets/17513790/269873f0-c47d-49c9-8462-035e3d24b464)
![image](https://github.com/Flysoft-Studio/QQNTim/assets/17513790/ce21e97b-8f47-4111-8efd-68133afd38f5)

**Comment by FlysoftBeta** [comment]
这似乎不是防撤回插件的问题，而是 QQNTim 的设置界面的问题，我会先调查一下此问题

**Comment by PaSSw0rds** [comment]
> 

好的，谢谢，目前我不安装任何插件的时候就不会有这个问题了
