### ISSUE TITLE
安装方式的变更需要启用PS脚本来自外部

### ISSUE THREAD

**Issue by PaSSw0rds** [FlysoftBeta/QQNTim#168]
![image](https://github.com/Flysoft-Studio/QQNTim/assets/17513790/ce858921-6c5c-403b-ac47-9fc34af29c21)

**Comment by PaSSw0rds** [comment]
需以管理员方式启动PS：

Set-ExecutionPolicy -ExecutionPolicy RemoteSigned

后即可安装

**Comment by PaSSw0rds** [comment]
![image](https://github.com/Flysoft-Studio/QQNTim/assets/17513790/37ace85b-bcc8-48b3-a45b-4bb5172ec6f9)

**Comment by FlysoftBeta** [comment]
请使用install.cmd安装而不是直接运行install.ps1
