### ISSUE TITLE
[Bug？] QQNTim 是否会导致 LiteLoader 插件的IPC拦截失效？

### ISSUE THREAD

**Issue by xh321** [FlysoftBeta/QQNTim#173]
我是LiteLoader上防撤回插件的开发者，有用户反馈安装了QQNTim后防撤回失效，在用户电脑上测试后，发现在有QQNtim存在的时候对webContents.send的劫持失效了，实际上没有执行我的函数。卸载QQNTim后恢复正常。

**Comment by FlysoftBeta** [comment]
是否可以分享一下实现代码？谢谢

**Comment by FlysoftBeta** [comment]
找到了

**Comment by FlysoftBeta** [comment]
由于不明原因，send 方法变成只读的了，不过我开了个 pr，你可以看下 https://github.com/xh321/LiteLoaderQQNT-Anti-Recall/pull/5

**Comment by xh321** [comment]
已合并
