### ISSUE TITLE
窗口控制按钮丢失？

### ISSUE THREAD

**Issue by HumanMus1c** [FlysoftBeta/QQNTim#174]
最小化、最大化、关闭，三个窗口控制按钮都没有了
![image](https://github.com/Flysoft-Studio/QQNTim/assets/46023154/81237c44-7958-4100-9cb3-229fd8feb525)

**Comment by FlysoftBeta** [comment]
不知道，目前没有任何一个插件有这个功能

**Comment by HumanMus1c** [comment]
装了QQNTim插件之后导入[https://github.com/Flysoft-Studio/QQNTim-Plugins-Galaxy](url)之后，窗口控制按钮丢失，测试了一下，是插件Mica背景有问题导致控制按钮丢失。
![image](https://github.com/Flysoft-Studio/QQNTim/assets/46023154/68ccbfce-f2b6-4afb-89b4-4106d8ab2a96)

**Comment by FlysoftBeta** [comment]
> 装了QQNTim插件之后导入[https://github.com/Flysoft-Studio/QQNTim-Plugins-Galaxy](url)之后，窗口控制按钮丢失，测试了一下，是插件Mica背景有问题导致控制按钮丢失。 ![image](https://user-images.githubusercontent.com/46023154/253966378-68ccbfce-f2b6-4afb-89b4-4106d8ab2a96.png)

这个插件没用了，建议删了
本来想把它标成已弃用的，但是后来忘了（）
