### ISSUE TITLE
怎样合并转发

### ISSUE THREAD

**Issue by Rei1mu** [FlysoftBeta/QQNTim#176]
rt, 如何实现，需要例子

**Comment by FlysoftBeta** [comment]
NT API 目前没有实现这个功能，不过你可以通过发送原始消息数据实现，例如 {"type":"raw","raw":{消息的原始数据}}

**Comment by FlysoftBeta** [comment]
这个原始数据可能需要你自己构造

**Comment by Rei1mu** [comment]
那个xmlContent的raw好像不行，试过（

**Comment by FlysoftBeta** [comment]
那就不知道了（（

**Comment by FlysoftBeta** [comment]
xmlContent是卡片消息吗

**Comment by Rei1mu** [comment]
是，所以求助，是否可行再说了 (

**Comment by FlysoftBeta** [comment]
也许是单独的api，你可以试试启用详细日志记录然后看看有没有相关的ipc消息
