### ISSUE TITLE
macOS 安装后提示A JavaScript error occurred in the main process

### ISSUE THREAD

**Issue by FredLin5** [FlysoftBeta/QQNTim#179]
<img width="632" alt="screenshot" src="https://github.com/Flysoft-Studio/QQNTim/assets/38588690/5645a341-c998-4b0a-87d6-8991a5474b86">

如图，在手动安装3.0.0版本后，打开QQ提示上述错误，无法启动QQ

安装方法参照Linux安装脚本，将`builtins`、`node_modules`文件夹和`qqntim.js`、`qqntim-renderer.js`文件复制到`/Applications/QQ.app/Contents/Resources/app/app_launcher`，并`package.json`文件中`index.js`替换为`qqntim.js`，启动后报错

QQNT版本为6.9.17-12118，macOS版本为Ventura 13.4.1 (c)

**Comment by FredLin5** [comment]
猜测可能是因为macOS版本与Linux版本目录结构不同导致的，这里放上macOS版本的目录结构
[QQ.txt](https://github.com/Flysoft-Studio/QQNTim/files/12077449/QQ.txt)

**Comment by FlysoftBeta** [comment]
请尝试使用这里提供的版本：https://github.com/Flysoft-Studio/QQNTim/actions/runs/5586839026

**Comment by FredLin5** [comment]
安装这个版本后可以启动并且插件也可以正常安装了

<img width="952" alt="截屏" src="https://github.com/Flysoft-Studio/QQNTim/assets/38588690/91aeb9f2-40a2-429c-93de-442195d1d1c3">

**Comment by FlysoftBeta** [comment]
好的,谢谢
