### ISSUE TITLE
[BUG?] 安装导致360极速浏览器X无法打开，LiteLoaderQQNT的插件市场无法正常显示插件

### ISSUE THREAD

**Issue by GuaiJieYo** [FlysoftBeta/QQNTim#203]
# QQNTim版本 3.1.3  
# QQNT版本 9.9.0-14569  
# 与LiteLoaderQQNT(Version 0.4.0)进行了共存  

# 过程描述:  
安装过程中经历了一次蓝屏 显示因为虚拟内存的原因 重启过后浏览器就无法开启 打开QQ后LiteLoaderQQNT的插件市场无法正常显示插件 通过uninstall.cmd卸载后 QQ打开无法正常渲染登陆页面  
我认为可能就是QQNTIM的原因 因为在安装此补丁之前 安装了LiteLoaderQQNT一切正常并没有什么问题 安装QQNTim才出现这一系列问题 希望开发者能够修复此BUG(?) 也希望能够和LiteLoaderQQNT有更好的兼容

**Comment by FlysoftBeta** [comment]
> # QQNTim版本 3.1.3
> # QQNT版本 9.9.0-14569
> # 与LiteLoaderQQNT(Version 0.4.0)进行了共存
> # 过程描述:
> 
> 安装过程中经历了一次蓝屏 显示因为虚拟内存的原因 重启过后浏览器就无法开启 打开QQ后LiteLoaderQQNT的插件市场无法正常显示插件 通过uninstall.cmd卸载后 QQ打开无法正常渲染登陆页面 我认为可能就是QQNTIM的原因 因为在安装此补丁之前 安装了LiteLoaderQQNT一切正常并没有什么问题 安装QQNTim才出现这一系列问题 希望开发者能够修复此BUG(?) 也希望能够和LiteLoaderQQNT有更好的兼容

你是从哪个版本升级的到3.1.3的？

**Comment by FlysoftBeta** [comment]
如果安装了3.1.3，建议先按照此处telegram频道公告进行退回操作https://t.me/qqntim/19

**Comment by GuaiJieYo** [comment]
> > # QQNTim版本 3.1.3
> > # QQNT版本 9.9.0-14569
> > # 与LiteLoaderQQNT(Version 0.4.0)进行了共存
> > # 过程描述:
> > 安装过程中经历了一次蓝屏 显示因为虚拟内存的原因 重启过后浏览器就无法开启 打开QQ后LiteLoaderQQNT的插件市场无法正常显示插件 通过uninstall.cmd卸载后 QQ打开无法正常渲染登陆页面 我认为可能就是QQNTIM的原因 因为在安装此补丁之前 安装了LiteLoaderQQNT一切正常并没有什么问题 安装QQNTim才出现这一系列问题 希望开发者能够修复此BUG(?) 也希望能够和LiteLoaderQQNT有更好的兼容
> 
> 你是从哪个版本升级的到3.1.3的？

release下载的 直装(第一次用)未升级

**Comment by FlysoftBeta** [comment]
> > > # QQNTim版本 3.1.3
> > > # QQNT版本 9.9.0-14569
> > > # 与LiteLoaderQQNT(Version 0.4.0)进行了共存
> > > # 过程描述:
> > > 安装过程中经历了一次蓝屏 显示因为虚拟内存的原因 重启过后浏览器就无法开启 打开QQ后LiteLoaderQQNT的插件市场无法正常显示插件 通过uninstall.cmd卸载后 QQ打开无法正常渲染登陆页面 我认为可能就是QQNTIM的原因 因为在安装此补丁之前 安装了LiteLoaderQQNT一切正常并没有什么问题 安装QQNTim才出现这一系列问题 希望开发者能够修复此BUG(?) 也希望能够和LiteLoaderQQNT有更好的兼容
> > 
> > 
> > 你是从哪个版本升级的到3.1.3的？
> 
> release下载的 直装(第一次用)未升级

3.1.3 已确定存在重大问题(已撤版)，请卸载qqntim,重装qq,安装qqntim 3.1.2
