### ISSUE TITLE
关于在Windows下安装了QQNT 64位之后的脚本架构判断问题

### ISSUE THREAD

**Issue by shawnpxtl** [FlysoftBeta/QQNTim#22]
腾讯自QQNT 9.8.3.13456开始同步提供64位版本，根据正常安装逻辑，64位程序安装时会安装到Program Files而非Program Files(x86)文件夹。但是安装时脚本一旦检测为64位系统就会默认将脚本安装到Program Files(x86)，这种逻辑在64位Windows下安装32位NTQQ时没问题，但是在64位NTQQ下尝试安装时会变成这样：

```
PS C:\Users\mclan\Desktop\qqntim-build> .\install.ps1
Do you want to install QQNTim (y/n)?: y
Killing QQ processes...
Copying files...
Patching entry...
Copy-Item : 找不到路径“C:\Program Files (x86)\Tencent\QQNT\resources\app\app_launcher\index.js”，因为该路径不存在。
所在位置 C:\Users\mclan\Desktop\qqntim-build\install.ps1:42 字符: 5
+     Copy-Item $EntryFile $EntryFileBackup -Force
+     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (C:\Program File...uncher\index.js:String) [Copy-Item], ItemNotFoundExce
   ption
    + FullyQualifiedErrorId : PathNotFound,Microsoft.PowerShell.Commands.CopyItemCommand
```

打开了脚本文件并稍作修改，再次安装提示成功，希望可以修改下安装逻辑。
附上版本号和截止到目前的最新64位版本[下载链接](https://dldir1.qq.com/qqfile/qq/QQNT/56c03ab0/QQ9.8.3.13720_x64.exe)：
![image](https://github.com/FlysoftBeta/QQNTim/assets/67815438/e3036359-214c-435b-bd82-437338664be8)

**Comment by FlysoftBeta** [comment]
感谢提醒，我以为QQNT只有32位版本:|
