### ISSUE TITLE
将Windows 平台的配置目录移动到%APPDATA%下

### ISSUE THREAD

**Issue by frg2089** [FlysoftBeta/QQNTim#35]
我认为`%APPDATA%\QQNTim`或`%LOCALAPPDATA%\QQNTim`或许是一个比`%USERPROFILE%\.qqntim`更好的保存这些内容的地方

**Comment by FlysoftBeta** [comment]
配置目录放在 AppData 下，对于不熟悉计算机的人来说可能不太友好
不过我会考虑添加一个环境变量，用于设置配置目录的位置

**Comment by frg2089** [comment]
一般来说 Windows 应用的配置目录啥的都是在这里面的。

或许可以在 Install.ps1 脚本中写一个在开始菜单中添加一个指向 `%APPDATA%\QQNTim` 的快捷方式..?

以及...我只是有点奇怪的赛博洁癖，看到你在直接往`%USERPROFILE%`里塞就顺便提一嘴而已。

**Comment by FlysoftBeta** [comment]
![图片](https://github.com/Flysoft-Studio/QQNTim/assets/49718840/1447314e-a851-4599-b654-867f3d3ed2a9)
