### ISSUE TITLE
Need Sender's uin

### ISSUE THREAD

**Issue by Rei1mu** [FlysoftBeta/QQNTim#49]
rt, uid不好分辨, 问问看有没有什么办法

**Comment by FlysoftBeta** [comment]
没有，不过 `getFriendsList` 里会返回 uin

**Comment by FlysoftBeta** [comment]
> rt, uid不好分辨, 问问看有没有什么办法

是不是通过 uid 获取 uin？

**Comment by Rei1mu** [comment]
> > rt, uid不好分辨, 问问看有没有什么办法
> 
> 是不是通过 uid 获取 uin？

可以是，也可以是直接uin，需要一个判断的办法

**Comment by FlysoftBeta** [comment]
> > > rt, uid不好分辨, 问问看有没有什么办法
> > 
> > 
> > 是不是通过 uid 获取 uin？
> 
> 可以是，也可以是直接uin，需要一个判断的办法

挺麻烦的，qq没这方面的接口

**Comment by Rei1mu** [comment]
> > > > rt, uid不好分辨, 问问看有没有什么办法
> > > 
> > > 
> > > 是不是通过 uid 获取 uin？
> > 
> > 
> > 可以是，也可以是直接uin，需要一个判断的办法
> 
> 挺麻烦的，qq没这方面的接口

好吧，不知道有没有算法或者什么

**Comment by FlysoftBeta** [comment]
> > > > > rt, uid不好分辨, 问问看有没有什么办法
> > > > 
> > > > 
> > > > 是不是通过 uid 获取 uin？
> > > 
> > > 
> > > 可以是，也可以是直接uin，需要一个判断的办法
> > 
> > 
> > 挺麻烦的，qq没这方面的接口
> 
> 好吧，不知道有没有算法或者什么

我估计没有，这种 uid 要不就是随机生成的，要不就是类似 sha 这种 hash 算法，不可逆的

**Comment by Rei1mu** [comment]
？有新方法了吗

**Comment by FlysoftBeta** [comment]
> ？有新方法了吗

有的

**Comment by FlysoftBeta** [comment]
抱歉，关联错issue了
