### ISSUE TITLE
有无聊天交互相关的插件例子啊

### ISSUE THREAD

**Issue by Rei1mu** [FlysoftBeta/QQNTim#5]
rt,待解答

**Comment by FlysoftBeta** [comment]
还没有，不过你可以描述一下你想实现的功能，我提供思路

**Comment by Rei1mu** [comment]
比如，如何接收聊天消息
然后发送消息
可实现socket或http通信之类的

**Comment by FlysoftBeta** [comment]
目前还没已经封装好了的发送和接收消息的接口，不过可以通过[拦截ipc](https://github.com/FlysoftBeta/QQNTim#%E6%8B%A6%E6%88%AA-ipc-1)实现，待会我可以给你写一个测试插件

**Comment by Rei1mu** [comment]
好，期待ing

**Comment by FlysoftBeta** [comment]
我创建了一个 [PR](https://github.com/FlysoftBeta/QQNTim/pull/9)，包含了 QQNT 插件 API 的施工进度

**Comment by Rei1mu** [comment]
实际上如果能通过ipc实现的话，会安全和方便很多

**Comment by FlysoftBeta** [comment]
- [x] 接口已添加（目前仅有发消息和收消息的功能）
- [x] 自动回复示例插件已添加（在 `examples` 文件夹下）

**Comment by Rei1mu** [comment]
nice, 感谢dalao

**Comment by 204065248** [comment]
很棒的项目，看好你哦
