### ISSUE TITLE
多开时发送消息无法区分账号

### ISSUE THREAD

**Issue by Rei1mu** [FlysoftBeta/QQNTim#54]
不知道有无解决办法，感觉可能区分插件路径会好一些了

**Comment by FlysoftBeta** [comment]
目前插件是在未登录之前就加载了，区分目录可能有些困难

**Comment by Rei1mu** [comment]
> 

所以设计感觉需要改改，比如插件路径改成ntqq运行目录（

**Comment by Rei1mu** [comment]
> 目前插件是在未登录之前就加载了，区分目录可能有些困难

这样我分目录装2个ntqq勉强也行

**Comment by FlysoftBeta** [comment]
可以在QQ启动前设置环境变量QQNTIM_HOME实现区分目录

**Comment by Rei1mu** [comment]
> 可以在QQ启动前设置环境变量QQNTIM_HOME实现区分目录

主要是在思考怎麽区分发消息.

**Comment by Rei1mu** [comment]
意思是，如果是双开，没办法指定哪个号发送消息?  在想 有什么办法

**Comment by FlysoftBeta** [comment]
关联错issue了，抱歉（）
使用方法：在 QQNTim 文件夹/plugins-user 下新建一个文件夹，将其命名为要生效的 QQ 号（uin），然后再把插件放进去即可。
