### ISSUE TITLE
尝试恢复 DevTools

### ISSUE THREAD

**Issue by FlysoftBeta** [FlysoftBeta/QQNTim#63]
QQ 的原生 DevTools 需要补全原版 Electron 的 resources.pak 才能使用 <(｀^´)> （仅为猜想，尚未测试）。

**Comment by Cranyozen** [comment]
尝试询问：现在的 DevTools 是修补后的嘛？还是说是残血的 DevTools
P.S. xx 已经验证了这个猜想

**Comment by FlysoftBeta** [comment]
> 尝试询问：现在的 DevTools 是修补后的嘛？还是说是残血的 DevTools P.S. xx 已经验证了这个猜想

残血版
