### ISSUE TITLE
防撤回目前9.9.0的bug

### ISSUE THREAD

**Issue by RX79XT** [FlysoftBeta/QQNTim#73]
QQNTim的防撤回功能在QQ界面发送消息会转圈 但是刷新后正常 导致认为消息没发出去发好几条

**Comment by FlysoftBeta** [comment]
移除了防撤回插件也一样吗？

**Comment by RX79XT** [comment]
移除后就正常了
________________________________
发件人: Flysoft ***@***.***>
发送时间: 2023年7月5日 23:36
收件人: Flysoft-Studio/QQNTim ***@***.***>
抄送: RX79XT ***@***.***>; Author ***@***.***>
主题: Re: [Flysoft-Studio/QQNTim] 防撤回目前9.9.0的bug (Issue #73)


移除了防撤回插件也一样吗？

―

**Comment by FlysoftBeta** [comment]
已修复
