### ISSUE TITLE
安装出现错误

### ISSUE THREAD

**Issue by histion** [FlysoftBeta/QQNTim#86]
ntqq版本： 9.9.0-14619 (64位)
[preload] succeeded. E:\1soft\QQNT\resources\app\versions\9.9.0-14619\wrapper.node
[preload] succeeded. E:\1soft\QQNT\resources\app\versions\9.9.0-14619\major.node
[preload] succeeded. E:\1soft\QQNT\resources\app\app_launcher\launcher.node
BetterQQNT: Initializing...
BetterQQNT: Start loading plugins.
BetterQQNT: Found plugin: LiteLoader 閰嶇疆鐣岄潰
BetterQQNT: Found plugin: 鑷畾涔?CSS 鏍峰紡
BetterQQNT: Found plugin: MSpring Theme
BetterQQNT: Found plugin: 鑷畾涔夌Щ闄や晶鏍?BetterQQNT: Found plugin: 闃叉挙鍥?BetterQQNT: Done! 5 plugins loaded!
BetterQQNT: Starting QQNT...
[preload] register done. launcher.node
[20548:0707/172850.215:ERROR:crashpad_client_win.cc(844)] not connected

**Comment by hugo-Miles** [comment]
我也是，安装卸载后再安装就这样了
`Do you want to install QQNTim (y/n)?: y
Killing QQ processes...
Copying files...
Patching package.json...
Installed successfully. Installer will exit in 5 sec.
[preload] process type:
[app]module file name: F:\QQNT\QQ.exe
[preload] hotupdate base version: 9.9.0-14569
[preload] hotupdate current version: 9.9.0-14619
[preload] install app version: 9.9.0-14569

[preload] succeeded. F:\QQNT\resources\app\versions\9.9.0-14619\wrapper.node
[preload] succeeded. F:\QQNT\resources\app\app_launcher\launcher.node
[preload] succeeded. F:\QQNT\resources\app\versions\9.9.0-14619\major.node
[preload] register done. launcher.node
[14512:0707/175733.179:ERROR:crashpad_client_win.cc(844)] not connected
`

**Comment by FlysoftBeta** [comment]
@histion @hugo-Miles 更新一下 1.5.0 试试（文档还没更新，新版要用 install.cmd 安装）
