### ISSUE TITLE
QQ cannot start after install it,version 1.5.0

### ISSUE THREAD

**Issue by SimpleJony** [FlysoftBeta/QQNTim#92]
![image](https://github.com/Flysoft-Studio/QQNTim/assets/108582874/823f312a-0f73-42af-a8c7-b954a1bd468c)

**Comment by xh321** [comment]
可以在安装脚本的目录（install.ps1那里，有node_modules的文件夹）手动npm init，然后npm i universalify，并把`node_modules`复制到`C:\Program Files\Tencent\QQNT\resources\app\app_launcher`里就行（那里已经有了一个`node_modules`，直接合并，不用替换文件）

**Comment by SimpleJony** [comment]
> 可以在安装脚本的目录（install.ps1那里，有node_modules的文件夹）手动npm init，然后npm i universalify，并把`node_modules`复制到`C:\Program Files\Tencent\QQNT\resources\app\app_launcher`里就行（那里已经有了一个`node_modules`，直接合并，不用替换文件）

好的我试一下，谢谢👍
